# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

kind-dependencies:
    - tox

transforms:
    - scriptworker_taskgraph.transforms.python_version:transforms
    - scriptworker_taskgraph.transforms.k8s_image:transforms
    - scriptworker_taskgraph.transforms.cached:transforms
    - taskgraph.transforms.cached_tasks:transforms
    - taskgraph.transforms.task:transforms

# TODO dependencies
#      env

job-defaults:
    description: "{name} k8s image builder py{python_version}"
    label: "{name}-k8s-image-builder-python{python_version}"
    run-on-tasks-for: ["action", "github-pull-request", "github-push"]
    worker-type: images
    worker:
        docker-image: {in-tree: 'k8s-image'}
        max-run-time: 3600
        docker-in-docker: true
        taskcluster-proxy: true
        chain-of-trust: true
        artifacts:
            - type: directory
              name: public/
              path: /builds/worker/artifacts/
        command:
            - sh
            - -lxce
            - >-
              /usr/local/bin/build_and_push.sh
    python-versions:
        - 38
    push-docker-image: false  # by-tasks_for, by-branch, by-level
    deploy-secret-url: http://taskcluster/secrets/v1/secret/project/releng/scriptworker-scripts/deploy
    # TODO copy image to artifacts
    # TODO scopes, metadata

jobs:
#    addonscript: {}
#    balrogscript: {}
#    beetmoverscript: {}
#    bouncerscript: {}
#    pushapkscript: {}
#    pushflatpakscript: {}
#    pushsnapscript: {}
#    shipitscript: {}
    signingscript:
        docker-repo: escapewindow/staging-signingscript
        # TODO docker-tag
        # TODO git head rev
        # TODO project_name (name)
        # TODO repo_url
#    treescript: {}
