# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

kind-dependencies:
    - docker-image

transforms:
    - scriptworker_taskgraph.transforms.tox:transforms
    - scriptworker_taskgraph.transforms.cached:transforms
    - taskgraph.transforms.cached_tasks:transforms
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms

job-defaults:
    run-on-tasks-for: ["action", "github-pull-request", "github-push"]
    worker-type: b-linux
    worker:
        docker-image: {in-tree: 'python{python_version}'}
        max-run-time: 1800
        artifacts:
            - type: directory
              name: public/
              path: /builds/worker/artifacts/
    python-versions:
        - 38
        - 37
    run:
        using: run-task
        cache-dotcache: false
        checkout:
            scriptworker: {}
        # sparse-profile: basestring/none
        # workdir:
        cwd: '{checkout}'
        command:
            - sh
            - -lxce
            - >-
              tox -e {name}-py{python_version}

jobs:
    client:
        description: scriptworker_client tox-py{python_version}
        digest-directories:
            - scriptworker_client
    configloader:
        description: config loader tox-py{python_version}
        digest-directories:
            - configloader
    iscript:
        description: iscript tox-py{python_version}
        digest-directories:
            - iscript
            - scriptworker_client
            - vendored/mozbuild
    signingscript:
        description: signingscript tox-py{python_version}
        digest-directories:
            - signingscript
            - vendored/mozbuild
