# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

kind-dependencies:
    - docker-image

transforms:
    - scriptworker_taskgraph.transforms.tox:transforms
    # XXX use cached_tasks if `when` doesn't work
    # - taskgraph.transforms.cached_tasks:transforms
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms

job-defaults:
    run-on-tasks-for: ["action", "github-pull-request", "github-push"]
    worker-type: b-linux
    worker:
        docker-image: {in-tree: 'python{python_version}'}
        max-run-time: 30
        artifacts:
            - type: directory
              name: public/
              path: /builds/worker/artifacts/
    python-versions:
        - 38
        - 37
    run:
        using: run-task
        cache-dotcache: false
        checkout:
            scriptworker: {}
        # sparse-profile: basestring/none
        # workdir:
        cwd: '{checkout}'
        command:
            - sh
            - -lxce
            - >-
              tox -e {name}-py{python_version}

jobs:
    signingscript:
        description: Signingscript tox-py{python_version}
